version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Asia/Singapore
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
