version: "3.9"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    environment:
      - TZ=Asia/Singapore
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    networks:
      - vidal_network

  influxdb:
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - vidal_network

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - vidal_network

  grafana:
    image: "grafana/${GRAFANA_IMAGE:-grafana:latest}"
    container_name: grafana
    user: "$UID:$GID"
    restart: always
    environment:
      TZ: "Asia/Singapore"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_INSTALL_PLUGINS: nline-plotlyjs-panel,volkovlabs-form-panel, briangann-gauge-panel, gapit-htmlgraphics-panel
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - vidal_network

  llm-python:
    image: "disquietly/llm-python:1.0"
    container_name: llm-python
    restart: always
    volumes:
      - ./LLM:/app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    networks:
      - vidal_network

  ollama:
    image: "ollama/ollama:latest"
    ports:
      - 11434:11434
    container_name: ollama
    restart: always
    environment:
      - TZ=Asia/Singapore
    networks:
      - vidal_network

volumes:
  chronograf-storage:

networks:
  vidal_network:
